### ISSUE TITLE
[Feature Request] More than 1 death sound effect

### ISSUE THREAD

**Issue by Yoni664** [Superkat32/YouWereSlain#13]
Hi! I like the idea of having a death sound effect, but I made 7 death sound effects because I dont want the same sound effect for every time I die hahahaha.
So I was wondering if maybe actually we can make random sounds with the resource pack and if the answer is yes, how we can do that?
I read that your planning to add a different sound with a Hardcore death, I dont know if maybe this request is redundant but Im posting it anyways.

Thx for the reading and sorry if I made a mistake wroting this, my english is not very good :D

**Comment by Yoni664** [comment]
Oh my gosh, forget this, I managed to make the random sounds work.
Im so proud of me lol

**Comment by Superkat32** [comment]
Glad you got it working! I couldn't remember if you could do it with just a resource pack or not and was just about to respond to this, lol.
